# Generated by Django 3.1 on 2020-09-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntastes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodocumento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('fechaprueba', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('numerodocumento', models.CharField(max_length=15)),
                ('codigoqr', models.CharField(max_length=5)),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTestPandemiaVuelo.tipodocumento')),
            ],
        ),
    ]
