# Generated by Django 3.1.1 on 2020-10-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTestPandemiaVuelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigoqr',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fechaprueba',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('codigoqr', models.ImageField(upload_to=None)),
                ('colorqr', models.CharField(max_length=15)),
                ('fechaprueba', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTestPandemiaVuelo.usuario')),
            ],
        ),
    ]
