# Generated by Django 3.1.1 on 2020-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTestPandemiaVuelo', '0002_auto_20201001_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='colorqr',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
