# Generated by Django 3.1.1 on 2020-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTestPandemiaVuelo', '0003_auto_20201001_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='codigoqr',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
