# Generated by Django 3.1 on 2020-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTestPandemiaVuelo', '0004_auto_20201001_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='codigoqr',
            field=models.ImageField(blank=True, null=True, upload_to='codigosqr'),
        ),
    ]
