# Generated by Django 3.1 on 2020-10-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTestPandemiaVuelo', '0005_auto_20201002_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
