# Generated by Django 3.1 on 2020-10-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTestPandemiaVuelo', '0006_remove_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntastestriesgos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Preguntastes',
            new_name='Preguntastest',
        ),
    ]
